[package]
name = "yew-example"
version = "0.1.0"
authors = ["Anthony Dodd <dodd.anthonyjosiah@gmail.com>"]
edition = "2018"

[dependencies]
shared = {path = "../shared", version = "0.1", features = ["nosend"]}
flnet = {path = "../../../flnet", version = "0.7", features = ["wasm"]}
flarch = {path = "../../../flarch", version = "0.7", features = ["wasm"]}

console_error_panic_hook = "0.1.6"
log = "0.4"
wasm-logger = "0.2"
tokio = {version = "1", features = ["time"]}
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
wee_alloc = "0.4.5"
ybc = "0.2"
yew = "0.18.0"
