[package]
name = "libc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flnet = {path = "../../../flnet", version = "0.7", features = ["libc"]}
flmodules = {path = "../../../flmodules", version = "0.7"}
flarch = {path = "../../../flarch", version = "0.7"}

shared = {path = "../shared", version = "0.1"}
tokio = {version = "1", features = ["full"]}
log = "0.4"