[package]
edition = "2021"
name = "shared"
version = "0.8.0"

[dependencies]
flmodules = {path = "../../../flmodules", version = "0.8"}
flarch = {path = "../../../flarch", version = "0.8"}

async-trait = "0.1"
log = "0.4"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
tokio = "1"
tokio-stream = "0.1"

[dev-dependencies]
flmodules = {path = "../../../flmodules", version = "0.8", features = ["testing"]}
tokio = {version = "1", features = ["rt-multi-thread"]}
