[package]
edition = "2021"
name = "shared"
version = "0.1.0"

[features]
nosend = ["flmodules/nosend", "flarch/wasm"]

[dependencies]
flmodules = {path = "../../../flmodules", version = "0.7"}
flnet = {path = "../../../flnet", version = "0.7"}
flarch = {path = "../../../flarch", version = "0.7"}

async-trait = "0.1"
log = "0.4"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
tokio = {version = "1"}
tokio-stream = "0.1"
wasm-timer = "0.2"

[dev-dependencies]
flnet = {path = "../../../flnet", version = "0.7", features = ["testing"]}
