name: Testing web_rtc
on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up cargo cache
      uses: actions/cache@v4
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          **/target/
        key: cargo-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-build-
          cargo

    - name: Run cargo_build
      shell: bash
      run: |
        make cargo_build

  cargo_test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up cargo cache
      uses: actions/cache@v4
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          **/target/
        key: cargo-test-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-test
          cargo-build

    - name: Run cargo_test
      shell: bash
      run: |
        make cargo_test

  make_test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up cargo cache
      uses: actions/cache@v4
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          **/target/
        key: cargo-make_test-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-make_test
          cargo-build

    - name: Install trunk
      run: which trunk || cargo install --locked trunk

    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: 'latest'

    - name: Run make_test
      shell: bash
      run: |
        make make_test
