name: Crate release
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - uses: actions-rs/cargo@v1
      continue-on-error: true
      with:
        command: publish
        args: --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --manifest-path flarch/Cargo.toml

    - uses: actions-rs/cargo@v1
      continue-on-error: true
      with:
        command: publish
        args: --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --manifest-path flarch/Cargo.toml

    - uses: actions-rs/cargo@v1
      continue-on-error: true
      with:
        command: publish
        args: --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --manifest-path flarch/Cargo.toml

    - uses: actions-rs/cargo@v1
      continue-on-error: true
      with:
        command: publish
        args: --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --manifest-path flarch/Cargo.toml
