name: Docker Build
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/.npm
          **/target/
          flbrowser/www/node_modules
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-
          ${{ runner.os }}-cargo-test-
          ${{ runner.os }}-cargo-test-build-

    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: 'latest'

    - name: Update build tag
      run: make update_version

    - name: Build signal server
      run: cd cli && cargo build --release -p flsignal

    - name: Build flnode for docker server
      run: cd cli && cargo build --release -p fledger

    - name: Build web server
      run: cd flbrowser && make build

    - name: Docker build signal
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: fledgre/flsignal
        registry: docker.io
        dockerfile: Dockerfile.signal
        directory: cli
        username: ${{ secrets.DOCKERHUB_NAME }}
        password: ${{ secrets.DOCKERHUB }}
        tags: latest

    - name: Docker build fledger
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: fledgre/fledger
        registry: docker.io
        dockerfile: Dockerfile.fledger
        directory: cli
        username: ${{ secrets.DOCKERHUB_NAME }}
        password: ${{ secrets.DOCKERHUB }}
        tags: latest

    - name: Docker build web
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: fledgre/web
        registry: docker.io
        dockerfile: Dockerfile.web
        username: ${{ secrets.DOCKERHUB_NAME }}
        password: ${{ secrets.DOCKERHUB }}
        tags: latest

  deploy:
    runs-on: ubuntu-latest
    needs: 
      - build

    steps:
    - name: Update signal.fledg.re
      uses: appleboy/ssh-action@master
      with:
        host: signal.fledg.re
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker-compose pull -q
          docker-compose down
          docker-compose up -d
