name: Testing web_rtc
on:
  pull_request:
    branches:
    - main

jobs:
  wasm-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-test-
          ${{ runner.os }}-cargo-build-

    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: 'latest'

    - name: Run flnet-wasm test
      run: |
        (cd cli/flsignal && cargo build && (cargo run &))
        cd arch/flnet-wasm
        make test

    - name: Run inter-arch test
      run: |
        cd test/webrtc-libc-wasm
        make all

  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
          node_modules
          ~/.npm
        key: ${{ runner.os }}-cargo-test-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-test-build
          ${{ runner.os }}-cargo-test-
          ${{ runner.os }}-cargo-build-

    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: 'latest'

    - name: Update build tag
      run: make update_version

    - name: Build all
      run: |
        ( cd shared && cargo build )
        make -C flbrowser build_local
        ( cd cli && cargo build )
        cd test
        (cd fledger-node && cargo build)
        (cd webrtc-libc-wasm && make all)