name: Testing web_rtc
on:
  pull_request:
    branches:
    - main

jobs:
  wasm-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/.npm
          **/target/
          flbrowser/www/node_modules
        key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-test-
          ${{ runner.os }}-cargo-build-

    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: 'latest'

    - name: Run inter-arch test
      run: |
        cd test/webrtc-libc-wasm
        make all

  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
          node_modules
          ~/.npm
        key: ${{ runner.os }}-cargo-test-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-test-build
          ${{ runner.os }}-cargo-test-
          ${{ runner.os }}-cargo-build-

    - name: Build and test all
      run: |
        make test_all